// Copyright 2020 Twitter, Inc.
// Licensed under the Apache License, Version 2.0
// http://www.apache.org/licenses/LICENSE-2.0

//
// Autogenerated by Scrooge
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//

import Foundation
import TwitterApacheThrift

public struct CollectiontThriftStruct: ThriftCodable, Equatable {
  let arrays: [Double]?
  let maps: [String:String]?
  let sets: Set<Int32>?

  enum CodingKeys: Int, CodingKey {
    case arrays = 1
    case maps = 2
    case sets = 3
  }
}
