// Copyright 2020 Twitter, Inc.
// Licensed under the Apache License, Version 2.0
// http://www.apache.org/licenses/LICENSE-2.0

//
// Autogenerated by Scrooge
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//

import Foundation
import TwitterApacheThrift

public struct FoundationThriftStruct: ThriftCodable, Equatable {
  let boolValue: Bool
  let doubleValue: Double
  let int16Value: Int16
  let int32Value: Int32
  let int64Value: Int64
  let stringValue: String

  enum CodingKeys: Int, CodingKey {
    case boolValue = 1
    case doubleValue = 2
    case int16Value = 3
    case int32Value = 4
    case int64Value = 5
    case stringValue = 6
  }
}
