//
// Autogenerated by Scrooge
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//

import Foundation
import TwitterApacheThrift

public struct OptionalThriftStruct: ThriftCodable, Equatable {
  let int16Value: Int16?
  let someBool: Bool
  enum CodingKeys: Int, CodingKey {
    case int16Value = 1
    case someBool = 2
  }
}
