// Copyright 2020 Twitter, Inc.
// Licensed under the Apache License, Version 2.0
// http://www.apache.org/licenses/LICENSE-2.0

//
// Autogenerated by Scrooge
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//

import Foundation
import TwitterApacheThrift

public struct SubobjectThriftStruct: ThriftCodable, Equatable {
  let value: OptionalThriftStruct?
  let intValue: Int16

  enum CodingKeys: Int, CodingKey {
    case value = 1
    case intValue = 2
  }
}
