// Copyright 2020 Twitter, Inc.
// Licensed under the Apache License, Version 2.0
// http://www.apache.org/licenses/LICENSE-2.0

//
// Autogenerated by Scrooge
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//

import Foundation
import TwitterApacheThrift

public struct UnionStruct: ThriftCodable, Equatable {
  let someUnion: MyUnion

  enum CodingKeys: Int, CodingKey {
    case someUnion = 1
  }
}
