//
// Autogenerated by Scrooge
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//

import Foundation
import TwitterApacheThrift

public struct UnionClassA: ThriftCodable, Equatable {
  let someString: String

  enum CodingKeys: Int, CodingKey {
    case someString = 1
  }
}
