//
// Autogenerated by Scrooge
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//

import Foundation
import TwitterApacheThrift

public struct UnionClassB: ThriftCodable, Equatable {
  let someInt: Int64

  enum CodingKeys: Int, CodingKey {
    case someInt = 1
  }
}
